mygpo/administration/group.py, mygpo/administration/tasks.py, mygpo/administration/views.py, mygpo/api/advanced/__init__.py, mygpo/api/advanced/directory.py, mygpo/api/backend.py, mygpo/podcasts/admin.py, mygpo/settings.py
Various fixes for errors in production.
=> Various fixes

doc/user/clients.rst
Updated Web Service Clients
Committer's note: this commit brings over [changes that were made to this page when it was hosted on the gPodder wiki](https://github.com/gpodder/gpodder/wiki/Web-Service-Clients/_compare/06db9e94fe3986a3e0b650ff8b8d57b4720b6572...c34cacbbdb8d7ec71a55582999c1e71ce06f7f18).
=> Updated Web Service Clients

mygpo/users/templates/registration/resent_activation.html
=> Typo fixed

doc/api/reference/devices.rst
Fix for https://github.com/gpodder/mygpo/issues/129
=> [doc] Fixed wrong http method in list devices api documentation

mygpo/web/templates/subscribe.html
=> Fixed typo

mygpo/locale/he/LC_MESSAGES/django.po
Translated using Transifex:
https://www.transifex.com/yaron/gpodder/
I'm not 100% sure about the "weeks, days, hours" strings at the end, the might crash the app so if needed I'll change this although this is the preferred native form for Hebrew speakers.
Fully compatible with the AntennaPod translation.
=> Added full Hebrew translation

mygpo/locale/nl/LC_MESSAGES/django.po
Translated using Transifex: https://www.transifex.com/yaron/gpodder/website/
=> Added Dutch translation

README.md, maintainer-needed.md
=> Maintainer needed

maintainer-needed.md
Made maintainer `requirements` before `tasks`.
Updated some articles.
Updated some words into a casual form.
Updated wishing/willing `will` into already understood, planned, factual `going to`.
=> Update for maintainer-needed.md

mygpo/web/templates/dashboard.html
Resolution for https://github.com/gpodder/mygpo/issues/229.
This is my first pull request to this project, so I hope all is well.
I've tested it on my system, and it works as intended.
=> Removed deprecated function (registerContentHandler)

mygpo/publisher/templates/publisher/info.html
New support email address on the info page.
=> Support email address change

mygpo/settings.py, requirements-setup.txt
=> Add support for Sentry

doc/dev/configuration.rst
Part of issue #274 to solve #268
=> Update configuration with QUERY_LENGTH_CUTOFF

mygpo/web/utils.py
Implemented by @webpigeon, fixes #232
=> Recognize CC licenses with https URLs (fixes #232)

doc/dev/configuration.rst, doc/dev/installation.rst, makefile
Hi,
I was interested in your project and followed the dev docs to get started. Well done on these docs, the process was really straightforward and painless (and I say this as someone who is not too familiar with Python)
I just noticed one or two typos and some other small things that I thought might make things easier.
=> Dev doc tweaks

mygpo/api/tests.py, mygpo/api/urls.py, mygpo/data/tests.py, mygpo/web/tests.py
Inspired by https://github.com/gpodder/mygpo/pull/269 I thought I'd try adding (a small number of rather basic) tests.
I also noticed some warnings while running the test suite and attempted to address these.
=> Add simple API search tests

doc/user/clients.rst
Updated AntennaPod as it now supports also the Episode Action
API.
Evidence: https://github.com/AntennaPod/AntennaPod/pull/706
=> Updated clients

mygpo/directory/management/commands/update-toplist.py
=> Fix update-toplist error

requirements.txt
See https://github.com/gpodder/mygpo/issues/574
=> Fixes issue 574

conf/gunicorn.conf.py
Balance for cpu count and memory
=> balance workers and threads

mygpo/users/urls.py
logout view to resolve to home.
=> Fix issue: 604

mygpo/users/views/user.py
=> Fix import error from Django 3 upgrade

mygpo/__init__.py, mygpo/podcasts/models.py, mygpo/subscriptions/__init__.py, mygpo/urls.py, mygpo/users/migrations/0016_alter_userprofile_twitter.py, requirements-setup.txt, requirements.txt
Various dependency updates and code reformatting.
=> Dependency updates

conf/gunicorn.conf.py, doc/dev/configuration.rst
* this makes running foreman as non-root easier
=> make LOGGING_DIR_GUNICRON a variable

mygpo/directory/tests.py, mygpo/directory/views.py
Simple change, not sure if new tests are overkill though.
=> allow adding of podcasts that exist without a link

mygpo/directory/tests.py, mygpo/locale/br/LC_MESSAGES/django.po, mygpo/locale/de/LC_MESSAGES/django.po, mygpo/locale/en/LC_MESSAGES/django.po, mygpo/locale/es/LC_MESSAGES/django.po, mygpo/locale/fr/LC_MESSAGES/django.po, mygpo/locale/he/LC_MESSAGES/django.po, mygpo/locale/it/LC_MESSAGES/django.po, mygpo/locale/ko/LC_MESSAGES/django.po, mygpo/locale/nb/LC_MESSAGES/django.po, mygpo/locale/nl/LC_MESSAGES/django.po, mygpo/locale/nl_NL/LC_MESSAGES/django.po, mygpo/locale/no/LC_MESSAGES/django.po, mygpo/locale/pl/LC_MESSAGES/django.po, mygpo/locale/pt/LC_MESSAGES/django.po, mygpo/locale/tr_TR/LC_MESSAGES/django.po, requirements.txt
=> Bump Django to 3.2.14

mygpo/publisher/templates/publisher/advertise.html
This hasn't been the case for many years now.
=> Remove outdated payment information
