.travis.yml
makefile
mygpo/settings.py
requirements.txt

Installing `psycopg2` fails with
````
cc -pthread -DNDEBUG -O2 -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION="2.7.1 (dt dec pq3 ext lo64)" -DPG_VERSION_NUM=90603 -DHAVE_LO64=1 -I/opt/python/pypy3.5-5.8.0/include -I. -I/usr/include/postgresql -I/usr/include/postgresql/9.6/server -c psycopg/adapter_binary.c -o build/temp.linux-x86_64-3.5/psycopg/adapter_binary.o -Wdeclaration-after-statement
cc -pthread -DNDEBUG -O2 -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION="2.7.1 (dt dec pq3 ext lo64)" -DPG_VERSION_NUM=90603 -DHAVE_LO64=1 -I/opt/python/pypy3.5-5.8.0/include -I. -I/usr/include/postgresql -I/usr/include/postgresql/9.6/server -c psycopg/adapter_datetime.c -o build/temp.linux-x86_64-3.5/psycopg/adapter_datetime.o -Wdeclaration-after-statement
psycopg/adapter_datetime.c: …
```

Enable Travis tests for Py 3.6, -dev and PyPy3

---

mygpo/core/slugs.py

I have no idea what a slug is, or what the object is, but I kept getting `obj not defined` errors when I did a search on my local mygpo server, and referring to the object variable seems an obvious fix to the problem.  
It seems to work on my installation anyway.

Fix 'obj not defined' error

---

.gitignore

.pytest_cache seems to be generated when running integration tests

Added .pytest_cache to .gitignore

---

static/clientconfig.json

the client config was returning a http address for the mygpo service.
This is a problem because if a client tries to login using this address, despite the redirect to https, the request would leave the user's machine unencripted containing the authentication info.

[clientconfig] Changed mygpo to https

---

mygpo/core/models.py
mygpo/podcasts/models.py

rt.
https://docs.djangoproject.com/en/2.1/ref/models/fields/#django.db.models.Field.null
https://docs.djangoproject.com/en/2.1/ref/models/fields/#django.db.models.Field.blank
It looks django admin use  _blank_ field  as 'required' flag.

fix bug - django admin - can't save nullable field of podcast with empty value.

---

doc/dev/installation.rst

Removing this from the docs as per @stefankoegl:
https://gpodder-net.slack.com/archives/CB5QBHTA8/p1564389664001700?thread_ts=1564274889.000400&cid=CB5QBHTA8

removing obsolete command from installation instructions.

---

doc/user/clients.rst

Update `doc/user/clients.rst` to reflect current status of android clients:
- Mark `SwallowCatcher` as abandoned. Download, source code and announcement links are all dead on their website.
- Mark `Detlef Gpodderson` as abandoned. Last commit to repo 5 years ago and the testing version of the app isn't available.
- Remove `FeedFarmer`. No signs that this app exists anymore.
- Mark `Podcatcher Deluxe` as dead. Link to website explains why it is no longer being maintained.
- Mark `SoudWaves` as abandoned. No commits or comments on issues since March 2018.
- Mark `Podax` as abandoned. README.md says as much.
- Mark `Podstars` as abandoned. No signs that this app exists anymore.
- Reorder android clients to put active ones at the top.
- Mark `Podcaster Deluxe` as deprecated to match the style …

Update doc/user/clients.rst to reflect current status

---

mygpo/administration/tests.py
mygpo/api/__init__.py
mygpo/api/legacy.py
mygpo/api/simple.py
mygpo/api/tests.py
mygpo/api/urls.py
mygpo/directory/templates/toplist.html
mygpo/test.py
mygpo/users/models.py

For #233
Some clean up:
Rename urls for toplist
Remove unused imports and variable assignment
Use "is not None" instead of "!= None"
Add SimpleAPITests to test views from mygpo.api.simple

Increase Simple API test coverage

---

mygpo/api/advanced/directory.py

Return empty string for "released" attribute of episode_data when no value is set.  Follows the same logic as "podcast_url" among others.
I'm using the python client library and "released" is in REQUIRED_KEYS which generates an error when no key is present in response. I'm assuming that the preference would be this proposed fix, as opposed to fixing in the client.

always return "released" attribute of episode_data

---

mygpo/administration/tests.py
mygpo/maintenance/tests.py

31c997edc3523345b78c4c1ece7241ce67b0865b updated `PodcastMerger.groups`
from expecting a dictionary of form/; "episode_id->[episodes]", to expecting a
dictionary of form: "episode_id->[episode_ids]". Update tests to reflect this
change.

Fix failing tests

---

mygpo/api/advanced/directory.py
mygpo/api/urls.py

Addressing "Add new podcast by API · Issue #219 · gpodder/mygpo"
If I add an URL that doesn't exist at all, e.g. https://example.com/podcast/feed.xml, [update_podcasts.AsyncResult](https://github.com/gpodder/mygpo/compare/master...SiqingYu:add-podcast-api?expand=1#diff-0e1a810669f7176d59c50d81ec348815R126) still returns successfully. Is this expected or not?
Example response for existed URL (automatically redirected):
```
{
"url": "https://changelog.com/podcast/feed",
"title": "The Changelog",
"description": "Conversations with the hackers, leaders, and innovators of software\ndevelopment. Hosts Adam Stacoviak and Jerod Santo face their imposter syndrome\nso you don’t have to. Expect in-depth interviews with the best and brightest\nin software engineering, open source, and leadership. …
```

API for adding new podcast.

---

doc/api/reference/directory.rst

The query parameters (podcast-url, episode-url) should be (podcast, url) instead.
See https://github.com/gpodder/mygpo/blob/master/mygpo/api/advanced/directory.py#L72 for reference.

Correct api/2/data/episode.json API parameters in documents.

---

doc/api/reference/directory.rst
doc/api/reference/general.rst
doc/api/reference/suggestions.rst
mygpo/api/advanced/directory.py
mygpo/api/templates/podcasts.xml

It would be great to have the author of podcasts returned in the API. I adapted the documentation and added the field to the API templates. Unfortunately, setting up the server is currently too much work for me, so this PR is **untested**. I would love if you could test and merge this, so [AntennaPod](https://github.com/AntennaPod/AntennaPod) can replace the URL in its search results with the authors, what should be a lot easier to understand for users (https://github.com/AntennaPod/AntennaPod/pull/3762).

Added author to API

---

mygpo/api/opml.py

Rebased from https://github.com/gpodder/mygpo/pull/35
Exported OPML example:
```xml
<?xml version="1.0" encoding="utf-8"?>
<opml version="2.0">
<head>
<title>mygpo</title>
<dateCreated>Thu, 06 Feb 2020 16:36:31 +0000</dateCreated>
</head>
<body>
<outline description="Stories of the human heart. A candid, unscripted conversation between two people about what's really important in life: love, loss, family, friendship. When the world seems out of hand, tune in to _StoryCorps_ and be reminded of the things that matter most." htmlUrl="https://www.npr.org/storycorps" text="StoryCorps" title="StoryCorps" type="rss" xmlUrl="https://www.npr.org/rss/podcast.php?id=510200"/>
</body>
</opml>
```
Format validated in Feedly.

OPML 2 support

---

doc/api/reference/directory.rst
mygpo/api/advanced/directory.py

Addressing https://github.com/gpodder/mygpo/issues/375

Remove `subscribers_last_week` field from directory API.

---

doc/user/clients.rst

If you find the time you could consider adding Escapepod to list of Android clients. It supports search by name on gpodder.

Add Escapepod to list of Android clients

---

Dockerfile
docker-compose.yml
makefile
mygpo/locale/fr/LC_MESSAGES/django.po
mygpo/settings.py

Giving an other try at #32, I ran into a couple of issues and here are fixes. Hope this helps!

Some fixes for the Docker setup

---

mygpo/podcasts/models.py
mygpo/publisher/urls.py
mygpo/web/tests.py

Currently it's not possible to load the publisher page for a podcast stub because of the following:
* Podcast's `next_update` property raises an exception when `last_update` is `None`
* Patterns in `publisher/urls.py` are in the wrong order, slug patterns shadow uuid patterns
This PR fixes these. I'm not sure where I should put those test cases..

Make publisher pages work for podcast stubs

---

mygpo/administration/tests.py
mygpo/api/legacy.py
mygpo/api/simple.py
mygpo/api/subscriptions.py
mygpo/podcasts/views/podcast.py
mygpo/subscriptions/tasks.py
mygpo/users/models.py
mygpo/users/tests.py

Asynchronously calling subscription tasks is currently broken on master (this includes subscribing to podcasts via the web interface).
This is since https://github.com/gpodder/mygpo/pull/24 was merged. Celery 4 uses `json` as the default task serializer, so all parameters need to be JSON serializable. Subscription tasks have arguments that aren't, thus an exception is thrown when they're scheduled.
This is my attempt at fixing this by changing task arguments so they use primary keys.

Make subscription tasks' arguments JSON serializable

---

README.md
doc/api/reference/directory.rst

This is a small update (IMHO) to gpodder.net documentation.
I noticed that links to Read the Docs used insecure HTTP URIs, whereas HTTPS is available. The change to the README updates these links to HTTPS.
In the [Directory API documentation](https://gpoddernet.readthedocs.io/en/latest/api/reference/directory.html) I noticed broken descriptions of query parameters in two endpoints, while other endpoints had correct descriptions.
Based on the working descriptions, I changed `::query` to `:query` in the ReStructuredText for the Directory API.

Use HTTPS URIs in README, fix query params in RST for Directory API docs

---

mygpo/api/advanced/sync.py

Linking the devices works but the very last step (`sync_user.delay(user)`) still fails with:
> TypeError: Object of type User is not JSON serializable
When using `sync_user.delay(user.pk) ` like it is used elsewhere, the request blocks indefinitely. https://github.com/gpodder/mygpo/blob/f4e9aedf6d15cfef9e3ac3682fa0b891767bfd8b/mygpo/users/views/device.py#L292
Closes #128

WIP: Fix sync API

---

.gitignore
mygpo/utils.py
requirements-dev.txt
requirements-test.txt
requirements.txt

This commit also updates versions of celery and black.

Pinning Django to 3.2 (LTS)

---

mygpo/locale/fr/LC_MESSAGES/django.po

Fix typo for french word "Accueil" (Home)

---

doc/user/clients.rst

The old link renders an error page: https://antennapod.org/documentation/general/gpodder

Fix link to AntennaPod documentation page on synchronization

---

doc/user/clients.rst

I stumbled upon two dead links:
- ~~Antennapod: There is a fitting page. Probably just the path changed.~~
- Podcast Addict: The link was leading to a personal page. I couldn't find a replacement and thus just removed the link.

replace dead links

---

mygpo/api/openapi.yaml

hi there! according to [the docs](https://gpoddernet.readthedocs.io/en/latest/api/reference/subscriptions.html#get-subscriptions-of-device), the method to get subscriptions by device should be updated in the openAPI summary - right now it is confusing, because the summary indicates something about `updating`, which doesn't seem to be correct.
thanks!

openAPI: fix method summary

---

mygpo/dumping.py
mygpo/podcasts/models.py
mygpo/settings.py

if a new setting `DUMP_TRAFFIC` is true, will dump api requests/responses to a `mygpo_dump` folder, for investigation.
Dump files must be handled cautiously because they contain user information (no password but subscriptions, play history, etc.).
Also keep activated for a short time only, to not saturate server storage (about 50MB per day).

hack to dump traffic for analysis
